### PR TITLE
Create yaml.h

### PR DESCRIPTION
**Pull request by OpposedDeception**
Added yaml.h header with data structutes and functions defined

### CODE REVIEW

**Comment by lapismyt** [comment]
I don't merge it now, because i don't know how we can use this from Python, sorry. Probably, i merge this later.

**Comment by UCYT5040** [comment]
@lapismyt Why should we ever merge this? If I'm not mistaken, this is a Python project, not a C/C++ project, so why rewrite existing Python files?

**Comment by lapismyt** [comment]
> @lapismyt Why should we ever merge this? If I'm not mistaken, this is a Python project, not a C/C++ project, so why rewrite existing Python files? Same for #34 

Yes, but compiled C/C++ much faster than Python

**Comment by OpposedDeception** [comment]
> > > @lapismyt Why should we ever merge this? If I'm not mistaken, this is a Python project, not a C/C++ project, so why rewrite existing Python files? Same for #34
> > 
> > C is inherently faster and provides safe memory allocation. Plus you can compile C code as a shared library and use it in Python.
> 
> > > @lapismyt Why should we ever merge this? If I'm not mistaken, this is a Python project, not a C/C++ project, so why rewrite existing Python files? Same for #34
> > 
> > Yes, but compiled C/C++ much faster than Python
> 
> Then why don't we design an entirely C/C++ server? I don't see a point in using multiple languages here.

Low-level functions can be written in C as an extension and used in Python, and code will be faster

**Pull request closed without merging**
