### PR TITLE
Update start.py

### PR DESCRIPTION
**Pull request by legitbox**
the change to python3 from python, ussually thats how linux responds to python version that is 3

### CODE REVIEW

**Comment by andiricum2** [comment]
Does that affect to windows decives?

**Comment by legitbox** [comment]
python3 works on windows too, if you install it the official way

**Comment by andiricum2** [comment]
It gives an error saying that you have to modify something from config to use it if you havent downloaded from microsoft store. Maybe we can add a something to handle what os is using the device to use one command or the other one. I will try it

**Comment by legitbox** [comment]
i could write the check if you want, i could cook it up today, its pretty
shrimple

**Comment by legitbox** [comment]
like if it finds pyhon on the ms store destination it switches to the
python3 mode

**Pull request merged**
